on:
  push:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Print base ref
        run: |
          echo "default_branch: ${{ github.event.repository.default_branch }}"
          echo "actual: ${{ github.ref_name }}"
