on:
  push:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Print base ref
        run: |
          echo "branch: $GITHUB_BASE_REF"
        env:
          GITHUB_BASE_REF: ${{ github.event.repository.default_branch }}
